### ISSUE TITLE
Add missing GroupMember resource

### ISSUE THREAD

**Issue by petergledhillinclusive** [pulumi/pulumi-databricks#19] opened 2022-07-30 09:40 UTC
## Add missing GroupMember resource

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When looking at the terraform documentation there should be an extra resource used to associate `databricks.User` with `databricls.Group`.  I am expecting that it would be called `databricks.GroupMember` but it is missing from this package.  

### Equivalent terraform resource: 
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group_member

### Example terraform
```
resource "databricks_group" "this" {
  display_name               = "Some Group"
  allow_cluster_create       = true
  allow_instance_pool_create = true
}

resource "databricks_user" "this" {
  user_name = "someone@example.com"
}

# -> The Pulumi equivalent of this resource is missing
resource "databricks_group_member" "vip_member" {
  group_id  = databricks_group.this.id
  member_id = databricks_user.this.id
}
```

### Affected area/feature

It looks like it's missing from the this projects `resource.go` file [file](https://github.com/pulumi/pulumi-databricks/blob/main/provider/resources.go).  

I don't know enough about pulumi dev to know if that's the only change needed or who should act on this.

**Comment by stack72** [comment] 2022-08-01 12:57
Hi @petergledhillinclusive

We have an issue with docs generation for this specific resource - we will look at how to overcome this issue and then re-enable it

Paul

**Comment by simonkarman** [comment] 2022-09-21 08:31
It seems like the issue keeps getting moved to the next milestone. Is there any indication that this will be picked up soon?

**Comment by viveklak** [comment] 2022-09-27 00:12
This will be fixed by #29

**Comment by simonkarman** [comment] 2022-10-12 07:55
Version v1.3.0 that was published last week (https://github.com/pulumi/pulumi-databricks/releases/tag/v1.3.0), which I think @lukehoban is referring to. I saw that in #29, #19 is closed, however as far as I can tell, it is not yet available.

Unfortunately I still cannot find a `databricks.NewGroupMember` resource. I'm using Go, and using the following dependency `github.com/pulumi/pulumi-databricks/sdk v1.3.0`.

**Comment by viveklak** [comment] 2022-10-12 16:22
Apologies - I missed that the resource is explicitly excluded due to doc generation issues: https://github.com/pulumi/pulumi-databricks/blob/main/provider/resources.go#L70. I will reopen.

**Comment by simonkarman** [comment] 2022-10-13 07:54
Is the root cause for the schema not being deterministic known? And if so, is that something I can fix?

**Closed** 2022-10-25 19:58 UTC
Labels: kind/bug, resolution/fixed
