### ISSUE TITLE
resource provider resource does not update on client secret rotation!!

### ISSUE THREAD

**Issue by edstancu** [pulumi/pulumi-databricks#594] opened 2024-09-17 08:59 UTC
### Describe what happened

Hi all,

I have a quite urgent issue. I am creating databricks provider using Azure credentials passed as environment variables like below:

```python
            databricks_provider = databricks.Provider(
                "databricks",
                auth_type="azure-client-secret",
                host=dbx.workspace_url.apply(lambda url: f"https://{url}"),
                azure_workspace_resource_id=dbx.id,
                azure_client_id=os.getenv("ARM_CLIENT_ID"),
                azure_tenant_id=os.getenv("ARM_TENANT_ID"),
                azure_client_secret=os.getenv("ARM_CLIENT_SECRET"),
                opts=pulumi.ResourceOptions(
                    depends_on=[dbx],
                    replace_on_changes=["azure_client_id", "azure_client_secret"],
                ),
            )
```

All worked perfect until we rotated the service principal secrets. The environment variables are taken values from github secret section and those secrets were updated to the correct ones after rotation. This is fine, as the github workflow does not fail, so definitely the details are correct.
However, if I run refresh on an existing stack using the databricks provider, the provider itself refreshes as normal. Then , all the follow up resources that are using this provider (external locations, schemas etc) are failing with error:

cannot read external location: failed during request visitor: inner token: Post "https://login.microsoftonline.com/xxxxxxxxxx/oauth2/token": AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'xxxxxxxxx'. See https://login.microsoftonline.com/error?code=7000215

The refresh is needed for our workflow before any preview or update. If i just run the preview it will of course detect the change and ask for update of the provider, but I want to prevent error on refresh in this cases

How can I solve this?
Thanks,
Elena

### Sample program

```python
            databricks_provider = databricks.Provider(
                "databricks",
                auth_type="azure-client-secret",
                host=dbx.workspace_url.apply(lambda url: f"https://{url}"),
                azure_workspace_resource_id=dbx.id,
                azure_client_id=os.getenv("ARM_CLIENT_ID"),
                azure_tenant_id=os.getenv("ARM_TENANT_ID"),
                azure_client_secret=os.getenv("ARM_CLIENT_SECRET"),
                opts=pulumi.ResourceOptions(
                    depends_on=[dbx],
                    replace_on_changes=["azure_client_id", "azure_client_secret"],
                ),
            )
```

### Log output

```
cannot read external location: failed during request visitor: inner token: Post "https://login.microsoftonline.com/xxxxxxxxxx/oauth2/token": AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'xxxxxxxxx'. See https://login.microsoftonline.com/error?code=7000215
```

### Output of `pulumi about`

```
[tool.poetry.dependencies]
python = "^3.9"
pulumi = "^3.109"
msal = "^1.27"
requests = "^2.32"
rauth = "0.7.3"

# Pulumi Plugin versions
# (must be consistent with versions in stack.py)
pulumi-azure-native = "^2.32"
pulumi-azuread = "^5.47"
pulumi-azure = "^5.68"
ediri-azapi = "~1.11" # AzAPI 1.12 is broken, see https://github.com/dirien/pulumi-azapi/issues/206
setuptools = "^70.0.0"
pulumi-databricks = "^1.45.0"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-09-18 12:19
Hi @edstancu. I'm sorry you have encountered https://github.com/pulumi/pulumi/issues/4981. You will need to run a `pulumi up` (to incorporate the new credentials) and then a `pulumi refresh` (to actually refresh) or you could attempt to edit your state directly.

**Comment by iwahbe** [comment] 2024-09-18 12:20
Since the problem isn't databricks specific, I'm going to close this issue. There is some discussion on workarounds in https://github.com/pulumi/pulumi/issues/4981, and I would definitely upvote the issue.

**Closed by iwahbe** 2024-09-18 12:20 UTC
Labels: kind/bug, resolution/by-design
